---
name: Build Radosgw
on:
  schedule:
    - cron: '0 0 * * 0'  # refresh ccache every sunday night
  pull_request:
    branches:
      - "s3gw"

  push:
    tags:
      - "s3gw-v*"

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ceph
          submodules: recursive

      - name: Create CCache Timestamp
        id: ccache_timestamp
        run: |
          echo "::set-output name=timestamp::$(date +%Y-%m-%d-%H:%M:%S)"

      - name: Cache CCache Files
        uses: actions/cache@v3.0.4
        with:
          path: ceph/build.ccache
          key: ccache-${{ steps.ccache_timestamp.outputs.timestamp }}
          restore-keys: |
            ccache-

      - name: Build radosgw binary and tests
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE/ceph:/srv/ceph \
            -e WITH_TESTS=ON \
            quay.io/s3gw/build-radosgw:latest

      - name: Run SFS unit tests
        run: |
          docker run \
            -v $GITHUB_WORKSPACE/ceph/build/bin:/radosgw/bin \
            -v $GITHUB_WORKSPACE/ceph/build/lib:/radosgw/lib \
            quay.io/s3gw/run-radosgw-tests

      - name: Install S3cmd
        run: |
          sudo apt-get update
          sudo apt-get install -y s3cmd

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          python3 -m pip install -r ceph/qa/rgw/store/sfs/tests/requirements.txt

      - name: Run Integration tests
        run: |
          set -e
          set -x

          source ceph/qa/rgw/store/sfs/tests/helpers.sh

          mkdir -p integration/storage
          CONTAINER=$(docker run --rm -d \
            -v $GITHUB_WORKSPACE/integration/storage:/data \
            -v $GITHUB_WORKSPACE/ceph/build/bin:/radosgw/bin \
            -v $GITHUB_WORKSPACE/ceph/build/lib:/radosgw/lib \
            -p 7480:7480 \
            quay.io/s3gw/run-radosgw \
              --rgw-backend-store sfs \
              --debug-rgw 1)

          wait_for_http_200 "http://127.0.0.1:7480"

          echo "Running Integration Tests:"
          cd ceph/qa/rgw/store/sfs/tests

          python3 -m unittest test-*.py

          docker kill $CONTAINER

      - name: Run smoke tests
        run: |
          set -e
          set -x

          source ceph/qa/rgw/store/sfs/tests/helpers.sh

          mkdir -p smoke/storage
          CONTAINER=$(docker run --rm -d \
            -v $GITHUB_WORKSPACE/smoke/storage:/data \
            -v $GITHUB_WORKSPACE/ceph/build/bin:/radosgw/bin \
            -v $GITHUB_WORKSPACE/ceph/build/lib:/radosgw/lib \
            -p 7480:7480 \
            quay.io/s3gw/run-radosgw \
              --rgw-backend-store sfs \
              --debug-rgw 1)

          wait_for_http_200 "http://127.0.0.1:7480"

          echo "Running Smoke Tests:"
          cd ceph/qa/rgw/store/sfs/tests
          ./sfs-smoke-test.sh 127.0.0.1:7480

          docker kill $CONTAINER
