---
name: Build Radosgw
on:
  schedule:
    - cron: '0 0 * * 0'  # refresh ccache every sunday night
  pull_request:
    branches:
      - "s3gw"

  push:
    tags:
      - "s3gw-v*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ceph
          submodules: recursive

      - name: Create CCache Timestamp
        id: ccache_timestamp
        run: |
          echo "::set-output name=timestamp::$(date +%Y-%m-%d-%H:%M:%S)"

      - name: Cache CCache Files
        uses: actions/cache@v3.0.4
        with:
          path: ceph/build.ccache
          key: ccache-${{ steps.ccache_timestamp.outputs.timestamp }}
          restore-keys: |
            ccache-

      - name: Build radosgw binary and tests
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE/ceph:/srv/ceph \
            -e NPROC=4 \
            -e WITH_TESTS=ON \
            quay.io/s3gw/build-radosgw:latest

      - name: Run SFS unit tests
        run: |
          docker run \
            -v $GITHUB_WORKSPACE/ceph/build/bin:/radosgw/bin \
            -v $GITHUB_WORKSPACE/ceph/build/lib:/radosgw/lib \
            quay.io/s3gw/run-radosgw-tests

      - name: Install S3cmd
        run: |
          sudo apt-get update
          sudo apt-get install -y s3cmd

      - name: Run smoke tests
        run: |
          mkdir storage
          docker run -d \
            -v $GITHUB_WORKSPACE/storage:/data \
            -v $GITHUB_WORKSPACE/ceph/build/bin:/radosgw/bin \
            -v $GITHUB_WORKSPACE/ceph/build/lib:/radosgw/lib \
            -p 7480:7480 \
            quay.io/s3gw/run-radosgw \
              --rgw-backend-store sfs \
              --debug-rgw 1

          sleep 5
          # ^ This is needed to give the gateway some time to boot up.
          # It also serves to make sure the gateway takes no more than 5 seconds
          # to boot up.

          echo "Running Tests:\n"
          cd ceph/qa/rgw/store/sfs/tests
          ./run-tests.sh
