---
name: Test s3gw
on:

  pull_request:
    branches:
      - "s3gw"

  push:
    branches:
      ci/s3tests-results
    tags:
      - "s3gw-v*"

jobs:
  tests:
    runs-on: self-hosted

    steps:

      - name: Checkout ceph
        uses: actions/checkout@v3
        with:
          path: ceph
          submodules: recursive

      - name: Checkout s3gw
        uses: actions/checkout@v3
        with:
          repository: aquarist-labs/s3gw
          path: s3gw
          submodules: false

      - name: Build s3gw Container Image
        run: |
          docker build \
            --build-arg CMAKE_BUILD_TYPE=RelWithDebugInfo \
            --build-arg NPROC=32 \
            --file s3gw/Dockerfile \
            --tag s3gw \
            .

          docker images

      - name: s3tr
        run: |
          set -x

          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $GITHUB_WORKSPACE/s3tr-out:/out \
            ghcr.io/irq0/s3tr:latest \
            run \
            --image s3gw:latest \
            /out/s3tr.json

      - uses: actions/upload-artifact@v3
        with:
          name: s3tr-results
          path: s3tr-out/s3tr.json

      - name: s3tr - new successes?
        run: |
          set -x
          docker run --rm \
            -v $GITHUB_WORKSPACE/s3tr-out:/out \
            -v $GITHUB_WORKSPACE/ceph:/ceph:ro \
            ghcr.io/irq0/s3tr:latest \
            analyze \
            new-successes \
            --known-good-file /ceph/qa/rgw/store/sfs/tests/fixtures/s3-tests.txt \
            /out/s3tr.json

      - name: s3tr - new failures?
        run: |
          set -x
          docker run --rm \
            -v $GITHUB_WORKSPACE/s3tr-out:/out \
            -v $GITHUB_WORKSPACE/ceph:/ceph:ro \
            ghcr.io/irq0/s3tr:latest \
            analyze \
            new-failures \
            --known-good-file /ceph/qa/rgw/store/sfs/tests/fixtures/s3-tests.txt \
            /out/s3tr.json
